basePath: /api
definitions:
  request.AudioListReq:
    properties:
      path:
        description: 路径
        type: string
    required:
    - path
    type: object
  request.FilePath:
    properties:
      path:
        description: 路径
        type: string
    type: object
  request.MkdirPath:
    properties:
      path:
        description: 路径
        type: string
    required:
    - path
    type: object
  request.OperateFilePath:
    properties:
      path:
        description: 路径
        type: string
    required:
    - path
    type: object
  request.Rename:
    properties:
      newName:
        type: string
      path:
        type: string
    required:
    - newName
    - path
    type: object
  request.TxtFile:
    properties:
      content:
        description: 内容
        type: string
      path:
        description: 创建文本文件的路径
        type: string
    required:
    - path
    type: object
  response.AudioInfo:
    properties:
      album:
        description: 专辑
        type: string
      albumArtist:
        description: 专辑艺术家
        type: string
      artist:
        description: 艺术家
        type: string
      comment:
        description: 评论
        type: string
      composer:
        description: 作曲
        type: string
      cover:
        description: 封面 base64
        type: string
      discNum:
        description: disc数
        type: integer
      discTotal:
        description: disc总数
        type: integer
      fileType:
        description: 文件类型
        type: string
      format:
        description: 标签格式
        type: string
      genre:
        description: 分类
        type: string
      isFolder:
        description: 是否是文件夹
        type: boolean
      lastModTime:
        description: 上次修改时间,单位为毫秒
        type: integer
      link:
        description: 静态链接
        type: string
      lyrics:
        description: 歌词
        type: string
      name:
        description: 文件名
        type: string
      path:
        description: 路径
        type: string
      raw:
        additionalProperties: true
        description: 原始标签数据
        type: object
      rootPath:
        description: 根路径
        type: string
      rootPathEncode:
        description: 根路径 urlsafe base64
        type: string
      size:
        description: 文件大小
        type: integer
      title:
        description: 标题
        type: string
      track:
        description: 音轨数
        type: integer
      trackTotal:
        description: 音轨总数
        type: integer
      year:
        description: 年代
        type: integer
    type: object
  response.FileInfo:
    description: 文件信息
    properties:
      isFolder:
        description: 是否是文件夹
        type: boolean
      lastModTime:
        description: 上次修改时间,单位为毫秒
        type: integer
      link:
        description: 静态链接
        type: string
      name:
        description: 文件名
        type: string
      path:
        description: 路径
        type: string
      rootPath:
        description: 根路径
        type: string
      rootPathEncode:
        description: 根路径 urlsafe base64
        type: string
      size:
        description: 文件大小
        type: integer
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  response.ServerInfoRes:
    properties:
      localIpList:
        description: 本地IP列表
        items:
          type: string
        type: array
      port:
        description: 本地端口
        type: integer
    type: object
host: 127.0.0.1:7888
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /audio/audioInfo:
    post:
      consumes:
      - application/json
      description: 获取指定文件的音频信息，图片会被转为base64，大于10mb则不进行转换，避免传输数据包过大
      parameters:
      - description: 音频文件定位信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AudioListReq'
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.AudioInfo'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取指定文件的音频信息
      tags:
      - audio
  /audio/audioList:
    post:
      consumes:
      - application/json
      description: 获取当前目录的音频信息列表，封面图片如果有会转为base64
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.AudioInfo'
                  type: array
              type: object
      summary: 获取当前目录的音频信息列表
      tags:
      - audio
  /audio/playAudio:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.AudioInfo'
              type: object
      summary: 播放音频，通过ffmpeg转换音频流
      tags:
      - audio
  /fileList/createTxt:
    post:
      consumes:
      - application/json
      description: 传入文件名和内容，创建txt文本文件
      parameters:
      - description: 创建txt需要的参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.TxtFile'
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 创建txt文本文件
      tags:
      - filelist
  /fileList/downloadItem:
    post:
      consumes:
      - application/json
      description: 传入fileitem下载指定项目，文件夹和文件的情况区别处理
      parameters:
      - description: 下载文件对应的信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.FileInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 下载项目
      tags:
      - filelist
  /fileList/filelist:
    post:
      consumes:
      - application/json
      description: 传入路径获取文件列表，不传参时返回根列表
      parameters:
      - description: 文件列表路径
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.FilePath'
      produces:
      - application/json
      responses:
        "200":
          description: 文件列表信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.FileInfo'
                  type: array
              type: object
      summary: 传入文件夹路径获取文件列表，不传参时返回根列表
      tags:
      - filelist
  /fileList/mkdir:
    post:
      consumes:
      - application/json
      description: 传入文件夹的路径，新建文件夹
      parameters:
      - description: 目录信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.MkdirPath'
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 新建文件夹
      tags:
      - filelist
  /fileList/removeItem:
    post:
      consumes:
      - application/json
      description: 传入路径，删除目录或文件
      parameters:
      - description: 路径
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.OperateFilePath'
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 删除目录或文件
      tags:
      - filelist
  /fileList/renameItem:
    post:
      consumes:
      - application/json
      description: 传入文件名和路径，重命名文件或文件夹
      parameters:
      - description: 重命名需要的参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Rename'
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 重命名文件或文件夹
      tags:
      - filelist
  /fileList/uploadMulti:
    post:
      consumes:
      - application/json
      description: 传入文件名和内容，创建txt文本文件
      parameters:
      - description: 创建txt需要的参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.TxtFile'
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 多文件上传
      tags:
      - filelist
  /server/getServerInfo:
    get:
      consumes:
      - application/json
      description: 获取本地ip等服务器信息
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.ServerInfoRes'
              type: object
      summary: 获取服务器信息
      tags:
      - server
  /user/getWebpermission:
    get:
      consumes:
      - application/json
      description: 获取前端权限信息
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 获取前端权限信息
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      description: 登录
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 登录
      tags:
      - user
  /video/getVttSubtitle:
    get:
      consumes:
      - application/json
      description: 将本地的ass，srt格式的字幕转成vtt返回字符串
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 获取vtt字幕
      tags:
      - video
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
