port: 8792
folderlist:
  - 'D:/coding'
userlist:
  - { username: 'mudssky', password: '123456' }

jwt:
  secret: eqweqeqe
  expires: 864000
zap:
  level: debug
  prefix: '[gfs]'
  format: console
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace

  ## 下面是lumberjack库相关的配置，用于日志写入文件
  filename: log/goserver.log
  # 最大日期，天数
  max-age: 30
  # 最大备份次数
  max-backup: 3
  # 单份日志大小 megabytes
  max-size: 500
  # show-line: true
  log-in-console: true

webpermission:
  # 新建文本，新建目录之类统一归类为write
  # 重命名和删除单独分类
  admin: ['write', 'read', 'rename', 'delete']
  user: ['write', 'read', 'rename']
  visitor: ['read', 'write']
  uploader: ['write']
