


# 测试ping接口
GET http://{{ $dotenv HOST}}/ping HTTP/1.1




###

GET http://{{ $dotenv HOST}}/files?path=/dsadassda HTTP/1.1


###

GET http://{{ $dotenv HOST}}/filelist HTTP/1.1


###

POST http://{{ $dotenv HOST}}/filelist HTTP/1.1


###
# @prompt folderPath
POST http://{{ $dotenv HOST}}/mkdir HTTP/1.1
Content-Type: application/json

{
	"folderPath":"{{folderPath}}"
}



###

POST http://{{ $dotenv HOST}}/uploadMulti HTTP/1.1
Content-Type: multipart/form-data;boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW